### ISSUE TITLE
GPU内存问题

### ISSUE THREAD

**Issue by ha1ha2hahaha** [ziqi-jin/finetune-anything#10]
您好！请问Fine-turn SAM 至少需要多少gb的gpu内存呢

**Comment by ziqi-jin** [comment]
> 

目前我测试，使用SAM最小的vit_b, bs=8, 需要29629MB的GPU内存
I tested that using the smallest vit_b of SAM, bs=8, requires 29629MB of GPU memory

**Comment by ziqi-jin** [comment]
> 您好！请问Fine-turn SAM 至少需要多少gb的gpu内存呢

目前我测试，使用SAM最小的vit_b, bs=8, 需要29629MB的GPU内存
I tested that using the smallest vit_b of SAM, bs=8, requires 29629MB of GPU memory
