### ISSUE TITLE
大佬，目标检测微调啥时候出来？（When you release the detection task? ）

### ISSUE THREAD

**Issue by Wulingtian** [ziqi-jin/finetune-anything#18]
如题

**Comment by ziqi-jin** [comment]
检测和实例分割后处理步骤稍复杂，预计本周支持抠图任务，下个月设计和实现检测任务。（The post-processing steps of detection and instance segmentation are a bit complicated. It is expected to support the matting task this week, and design and implement the detection task next month.）
