### ISSUE TITLE
语义分割推理代码何时发布？

### ISSUE THREAD

**Issue by Wulingtian** [ziqi-jin/finetune-anything#20]
迫不及待想试试！

**Comment by ziqi-jin** [comment]
请再等一等，哈哈，这个库是业余时间做的，可能会慢一些，后面我会在Readme中放出支持计划的时间线，当我完成推理部分将会在这个issue中告知你。 (Please wait a little longer, haha, I make this repository part-time, so it may be slower， I will release the timeline of the support plan in the Readme later. I will let you know about this issue when I finish the reasoning part)
