### ISSUE TITLE
请问有支持MobileSAM的计划吗？

### ISSUE THREAD

**Issue by Wulingtian** [ziqi-jin/finetune-anything#23]
MobileSAM链接如下：
https://github.com/ChaoningZhang/MobileSAM

**Comment by ziqi-jin** [comment]
我也对这个项目很感兴趣，还没有细致的看他的模型结构，后面会有集成此模型的计划。(I am also very interested in this project. I haven't looked at its model structure in detail yet, and there will be a plan to integrate this model later.)
