### ISSUE TITLE
Finetune on custom task

### ISSUE THREAD

**Issue by Jtao0818** [ziqi-jin/finetune-anything#29]
Thanks for your excellent work.
 I am trying to finetune the SAM model on the Salient Object Detection task. I implement my custom dataset based on `BaseSemanticDataset` by replacing my own `dataset_dir`and replace ce loss with BCEWithLogitLoss to fix some bug. 
However, the loss seems strange. Do you have any idea of this? 

> iteration : 1, bce : -218.368408203125, total_loss : -109.1842041015625, time : 0
iteration : 3, bce : -2733.0740509033203, total_loss : -1366.5370254516602, time : 0
iteration : 5, bce : -67497.31298828125, total_loss : -33748.656494140625, time : 0
iteration : 7, bce : -19547019.328125, total_loss : -9773509.6640625, time : 0
iteration : 9, bce : -303343570888.0, total_loss : -151671785444.0, time : 0
iteration : 11, bce : -6.906153512921124e+19, total_loss : -3.453076756460562e+19, time : 0
iteration : 13, bce : -inf, total_loss : -inf, time : 0
iteration : 15, bce : nan, total_loss : nan, time : 0
iteration : 17, bce : nan, total_loss : nan, time : 0
iteration : 19, bce : nan, total_loss : nan, time : 0
iteration : 21, bce : nan, total_loss : nan, time : 0

**Comment by ziqi-jin** [comment]
The nan is caused by the loss being too large or too small. You can limit the size of the loss through the weight, or normalize the loss. The loss weight can be modified in the yaml file in config/
