### ISSUE TITLE
semantic segmentation

### ISSUE THREAD

**Issue by 1105430565** [ziqi-jin/finetune-anything#3]
How to predict N classes in SemSegHead？

**Comment by ziqi-jin** [comment]
> I am writing the code for N classes prediction and the pipeline, please wait a few days. My idea is to change the MLP part in SemSegHead.

I am writing the code for N classes prediction and the pipeline, please wait a few days. My idea is to change the MLP part in SemSegHead.

**Comment by ziqi-jin** [comment]
> How to predict N classes in SemSegHead？

I am writing the code for N classes prediction and the pipeline, please wait a few days. My idea is to change the MLP part in SemSegHead.

**Comment by ziqi-jin** [comment]
> How to predict N classes in SemSegHead？

The SemSegHead has been released now, you can check it , If you have other idea about modify the structure of SAM, you are welcome to submit a PR. Thanks for your attention.
