### ISSUE TITLE
mIoU

### ISSUE THREAD

**Issue by eternal-f1ame** [ziqi-jin/finetune-anything#35]
I would like to know, from anyone who has used the available script for a semantic seg task.
What was the best mIoU you could obtain. And using how many epochs/batch size.

**Comment by ziqi-jin** [comment]
For the voc dataset of the semantic segmentation task, bs is set to 8, which requires tens of thousands of iterations. mIOU can reach 79. I have not adjusted the parameters on purpose. The more iterations, the better the effect. $ epoch = iterations \times batchsize \divide photonumber $
