### ISSUE TITLE
Update code train

### ISSUE THREAD

**Issue by dFuong** [ziqi-jin/finetune-anything#4]
Please release training code !

**Comment by ziqi-jin** [comment]
> Please release training code !

Okay, I've been a little busy recently. The complete code will be updated in the next week or two

**Comment by dFuong** [comment]
Thanks your reply.

**Comment by ziqi-jin** [comment]
> Thanks your reply.

you are welcome.

**Comment by ziqi-jin** [comment]
> 

The semantic segmentation process code is available now, the other tasks will be released later
