### ISSUE TITLE
完整代码

### ISSUE THREAD

**Issue by kaigelee** [ziqi-jin/finetune-anything#5]
感谢您非常棒的工作，请问完整代码何时能够上传？

**Comment by ziqi-jin** [comment]
> 感谢您非常棒的工作，请问完整代码何时能够上传？

代码正在编辑测试中，后续还有相关数据集的实验结果。第一版大概一个月之内可以完成，先支持语义分割任务。

The code is being edited and tested, and there will be experimental results on related datasets in the future. The first version can be completed within about a month, first supporting semantic segmentation tasks.

**Comment by kaigelee** [comment]
> 已支持VOC数据集上的语义分割，后续会开发自定义数据集。

感谢感谢！！期待你放出实验结果。
