### ISSUE TITLE
Semantic Segmentation

### ISSUE THREAD

**Issue by Kalfredwv** [ziqi-jin/finetune-anything#6]
Thanks for you great work. I wonder whether the code for semantic segmentation had been finished.

**Comment by ziqi-jin** [comment]
> Thanks for you great work. I wonder whether the code for semantic segmentation had been finished.

please refer to this issue, https://github.com/ziqi-jin/finetune-anything/issues/5#issuecomment-1562276527

**Comment by ziqi-jin** [comment]
Now FA can run the Semantic Segmentation on VOC. The Customized Dataset will be released later, so I close this issue
